apiVersion: v1
appVersion: "6.12.1"
description: Web platform for building complex solutions, websites and blogs.
name: exp
version: 0.1.0
home: https://enonic.com
sources:
- https://github.com/diegopasten/helm-enonic-xp
maintainers:
- name: "Diego Pasten"
  email: "diego.pasten@gmail.com"
keywords:
- cms
- nosql
- application
- pwa
- web
- blog
- java
- cluster
