apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
      app: {{ template "fullname" . }}
