apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: {{ template "fullname" . }}
    spec:
        containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: "CLUSTER_NAME"
              value: {{ template "fullname" . }}-cluster
            - name: "DISCOVERY_SERVICE"
              value: {{ template "fullname" . }}
            ports:
            - containerPort: 8080
              name: {{ template "fullname" . }}
              protocol: TCP
            volumeMounts:
            - mountPath: "/xp"
              name: exp-persistent-storage
        volumes:
          - name: exp-persistent-storage
            gcePersistentDisk:
              pdName: {{ template "fullname" . }}-pdisk
              fsType: ext4
